name: "nocjk Action"
description: "Run nocjk command easily in GitHub Actions"
inputs:
  args:
    description: "Arguments for nocjk command"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "check-circle"
  color: "blue"
